# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/ruslanpashkov/novapass/discussions
    about: Please ask and answer questions here
