name: Lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - uses: actions/checkout@main

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run compile

      - name: Run ESLint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check
